name: Run Tests

on:
  push:
    branches: [ master ]

jobs:
  test-linux:
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v2

      - run: mkdir build
      - run: cmake ../
        working-directory: build
      - run: make
        working-directory: build
      - run: ./my_test
        working-directory: build
        
  test-windows:
    runs-on: [windows-latest]
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: ilammy/msvc-dev-cmd@v1
      
      - run: mkdir build
      - run: cmake ..
        working-directory: build
      - run: devenv my_core_lib.sln /build Debug
        working-directory: build
      - run: .\build\Debug\my_test.exe
