name: Run Tests

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v2

      - run: mkdir build
      - run: cmake ../
        working-directory: ${{GITHUB_WORKSPACE}}/build
      - run: make
        working-directory: ${{GITHUB_WORKSPACE}}/build
      - run: ./my_test
        working-directory: ${{GITHUB_WORKSPACE}}/build
